### PR TITLE
utils.controls.Digest

### PR DESCRIPTION
**Pull request by DavidDurman**
image

### CODE REVIEW

**Comment by vtalas** [comment]
test: 

flow https://my.qa.appmixer.com/designer/f41f62c9-f4d3-4fa2-bab3-62ecb5cc2cb5/7f7ffa5c-a36d-4755-86e1-39ccb8b258b7
image

input
image


flow interates through the input array values, Digest has the threshold set to 2, output type: one at a time


results:
values `11111...` and `2222...` get duplicated: 
image

The `lock` should be implemented to prevent this behavior

**Comment by vtalas** [comment]
the `index` on the output: 
image

It's the index within the threshold, shouldn't be better to implement the `total index` instead?

**Comment by DavidDurman** [comment]
Lock: implemented.
@vtalas I don't see how "total index" would be useful? The index is just the standard index we have for array-type of outputs.

**Review by vtalas — APPROVED** [review]

**Comment by RamBachkheti** [comment]
Issue: Getting "Invalid Characters, got value: undefined" while starting the flow when valid values for "Minute" and "Hour" text values are set, please see the following image:
- 
Screenshot 2024-10-28 at 12 00 18 PM
Screenshot 2024-10-28 at 11 59 41 AM

**Comment by DavidDurman** [comment]
Fixed in https://github.com/clientIO/appmixer-connectors/pull/288

**Pull request merged**
