### PR TITLE
Converters: improve CSV to HTML/JSON and JSON to CSV/HTML converters to use streams  

### PR DESCRIPTION
**Pull request by vtalas**
- [x] CSV2HTML
- [x] CSV2JSON
- [x] JSON2CSV
- [x] JSON2HTML

**JSON2HTML, CSV2HTML**
  You can define a custom HTML transformer by creating a new instance of the Transform class in htmlTransforms.js.
  htmlTransforms:
  ```js 
    const { Transform } = require('stream');
    
    module.exports = {
    
        myHtmlTransform: {
            jsonPath: '*', // https://www.npmjs.com/package/JSONStream#jsonstreamparsepath
            transform: () => {
                return new Transform({
                    writableObjectMode: true,
                    readableObjectMode: false,
                    transform(chunk, encoding, callback) {
    
                        // implementation of your custom transformation
                        callback();
                    },
                    final(callback) {
                        callback();
                    }
                });
            }
        }
    };
  ```
configure the transformer type in the Backoffice: 
`JSON2HTML_TRANSFORMER`, `CSV2HTML_TRANSFORMER`

example
image

**Testing converters locally:** 
You can test the converters locally by importing their implementation and mocking Appmixer's context object. This approach can be useful when creating your custom transformers.

```js
const fs = require('fs');
const { pipeline } = require('stream');
const { promisify } = require('util');
const converters = require('../../../../appmixer/utils/converters/converters');
const pipelineAsync = promisify(pipeline);

const mem = () => {
    const formatMemoryUsage = (data) => `${Math.round(data / 1024 / 1024 * 100) / 100} MB`;

    const memoryData = process.memoryUsage();

    const memoryUsage = {
        rss: `${formatMemoryUsage(memoryData.rss)} -> Resident Set Size - total memory allocated for the process execution`,
        heapTotal: `${formatMemoryUsage(memoryData.heapTotal)} -> total size of the allocated heap`,
        heapUsed: `${formatMemoryUsage(memoryData.heapUsed)} -> actual memory used during the execution`,
        external: `${formatMemoryUsage(memoryData.external)} -> V8 external memory`
    };

    console.log(memoryUsage);
};

const contextMock = {

    getFileReadStream: async (sourceFile = 'sample.json') => {

        const path = __dirname + '/' + sourceFile;
        console.log('CONTEXT-MOCK.getFileReadStream', path);
        return fs.createReadStream(path);
    },

    getFileInfo: async (sourceFileId) => {
        return {
            filename: sourceFileId
        };
    },

    saveFileStream: async (filename, stream) => {

        const path = __dirname + '/results/' + filename;
        console.log('CONTEXT-MOCK.saveFileStream', path);
        const writeStream = fs.createWriteStream(path);
        await pipelineAsync(
            stream,
            writeStream
        );
    },

    saveFile: async (filename, mimeType, buffer) => {

        const path = `${__dirname}/results/orig.${filename}`;
        console.log('CONTEXT-MOCK.saveFile', path);
        await fs.promises.writeFile(path, buffer);
        return {
            fileId: 'id'
        };
    },
    log: console.log
};
const csvToJson = async function(sourceFileId) {

    console.log('----- CSV2JSON ----- ');

    const stream = await converters.csvToJson(contextMock, sourceFileId);
    await contextMock.saveFileStream(sourceFileId, stream);

    mem();
};

const jsonToHtml = async function(sourceFileId) {

    console.log('----- JSON2HTML ----- ');

    const stream = await converters.jsonToHtml(contextMock, sourceFileId);
    await contextMock.saveFileStream(`${sourceFileId}.html`, stream);
    mem();
};

(async function() {
    try {
        await csvToJson('csv2json-sample.csv');
        await jsonToHtml('json2html-sample.json');
    } catch (e) {
        console.error('____CAUGHT ERROR', e);
    }
}());

```

### CODE REVIEW

**Review by jirihofman — APPROVED** [review]

**Review by jirihofman — APPROVED** [review]

**Comment by RamBachkheti** [comment]
@vtalas : I am observing following issue while testing the above converters with large file (not sure if this is expected behavior):

Issue 1: [CSV2HTML][CSV2JSON] Getting "Input Queue timed out calling receive method" error, please see the following images:
- Screenshot 2024-09-03 at 6 50 25 PM
Screenshot 2024-09-03 at 7 42 25 PM

**Test Flow:**
- https://my.stg.appmixer.com/designer/dac0ba37-acf8-4a0e-a020-c83c6e7ef3bd/fff84b66-9a6c-48eb-a91a-c76a927b50a6
-

**Test File:**
- [SampleCSVFile_53000kb.csv](https://github.com/user-attachments/files/16849638/SampleCSVFile_53000kb.csv)

**Comment by vtalas** [comment]
> @vtalas : I am observing following issue while testing the above converters with large file (not sure if this is expected behavior):
> 
> Issue 1: [CSV2HTML][CSV2JSON] Getting "Input Queue timed out calling receive method" error, please see the following images:
> 
> * Screenshot 2024-09-03 at 6 50 25 PM
>   Screenshot 2024-09-03 at 7 42 25 PM
> 
> **Test Flow:**
> 
> * https://my.stg.appmixer.com/designer/dac0ba37-acf8-4a0e-a020-c83c6e7ef3bd/fff84b66-9a6c-48eb-a91a-c76a927b50a6
> 
> **Test File:**
> 
> * [SampleCSVFile_53000kb.csv](https://github.com/user-attachments/files/16849638/SampleCSVFile_53000kb.csv)

it's ready for re-test

**Comment by RamBachkheti** [comment]
@vtalas: I am observing following issue

Issue 1: [JSON2CSV] converter is showing "jsonPath is not defined" error, please see the following image:
- 
Screenshot 2024-09-17 at 6 01 43 PM

<hr>

Issue 2: [JSON2HTML] Showing "Missing fileId param" error when fileID is already provided, please see the following image:
- 
Screenshot 2024-09-17 at 6 02 45 PM

**Test Flow:**  https://my.stg.appmixer.com/designer/b7682242-663a-40c6-861d-ef1604a8097f/72ed5486-fd8b-45eb-a2ec-b13b25d09b05

**Comment by RamBachkheti** [comment]
@vtalas : I am observing following issue:

Issue 1: The 'Message' field is displaying curly braces ({}), and I'm not sure what that indicates, please see the following image:
- Screenshot 2024-09-18 at 11 43 39 AM
<hr>

Issue 2: The tooltip text needs to be updated to indicate that the content field cannot be left blank, so it's no longer possible to create an empty CSV file, please see the following image:
- 
Screenshot 2024-09-18 at 12 02 20 PM

**Comment by RamBachkheti** [comment]
@vtalas: Still observing the above reported issues on staging environment too. Can you please confirm if the fix has been merged on staging or not ?

**Comment by vtalas** [comment]
> @vtalas: Still observing the above reported issues on staging environment too. Can you please confirm if the fix has been merged on staging or not ?

have you installed the latest version of converters (appmixer.utils.converters )?

**Comment by RamBachkheti** [comment]
@vtalas: Yes, even after upgrading the converter, I am still observing the above reported Issues, please see the following video:
- https://github.com/user-attachments/assets/49a1375d-f0e3-4abb-a1ca-da09ef2ef50c

**Comment by vtalas** [comment]
> @vtalas: Yes, even after upgrading the converter, I am still observing the above reported Issues, please see the following video:
> 
> * https://github.com/user-attachments/assets/49a1375d-f0e3-4abb-a1ca-da09ef2ef50c
> 
> **Test Flow:** https://my.stg.appmixer.com/designer/b7682242-663a-40c6-861d-ef1604a8097f

@RamBachkheti  please be careful with the version numbers. the latest version is the 1.3.2.  
We need to keep an eye on version updates as well. If the latest version is not available in the backoffice, please raise a ticket in the appmixer-marketplace repository. Additionally, we will make a note of the latest version in the tickets which are ready for testing: 

for example 
" @RamBachkheti 1.3.2 is ready for testing " 

you don't need to raise a ticket for now, it's already have been working on https://clientio.slack.com/archives/C5JVBTZ1V/p1727085006755179

**Comment by vtalas** [comment]
@RamBachkheti  the latest version is ready for re-test (v1.3.2)

**Comment by RamBachkheti** [comment]
@vtalas: The latest version I can see is 1.3.3, which is already installed on staging environment. So testing the connected with 1.3.3 version.

**Comment by RamBachkheti** [comment]
Verified the fix on Staging. 
 
 Test Flow: 
 https://my.stg.appmixer.com/designer/b393766e-60ec-4392-a95c-c03c8415c207/3f412f7d-8e24-49fe-9068-0931ff34ecc8

**Pull request merged**
